### ISSUE TITLE
无法获取知乎新闻

### ISSUE THREAD

**Issue by Polaris-Koi** [LinHeLurking/mirai-news-reporter#13]
2022-03-17 19:03:00 E/Reporter: java.net.MalformedURLException: no protocol:
java.net.MalformedURLException: no protocol:
        at java.base/java.net.URL.<init>(URL.java:645)
        at java.base/java.net.URL.<init>(URL.java:541)
        at java.base/java.net.URL.<init>(URL.java:488)
        at online.ruin_of_future.reporter.NewsCrawler.newsToday(NewsCrawler.kt:93)
        at online.ruin_of_future.reporter.ReporterPlugin$onEnable$sendNewsToTarget$1.invokeSuspend(App.kt:96)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:147)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by LinHeLurking** [comment]
已于 1.3.1 修复

**Comment by LinHeLurking** [comment]
之前的 CI 有问题，直接下载最新版的吧：
https://github.com/LinHeLurking/mirai-news-reporter/releases/tag/latest
