### ISSUE TITLE
推送番剧时报错

### ISSUE THREAD

**Issue by aipiao-gh** [LinHeLurking/mirai-news-reporter#22]
2022-12-04 07:00:04 V/Bot: Group <- 早上好呀, 这是今天的 B 站番剧 \n( •̀ ω •́ )✧
2022-12-04 07:00:05 E/Reporter: online.ruin_of_future.reporter.crawler.NoAnimeException: Not found info for date: 12-4
online.ruin_of_future.reporter.crawler.NoAnimeException: Not found info for date: 12-4
	at news-reporter-1.4.0.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.animeByDate(AnimeCrawler.kt:207)
	at news-reporter-1.4.0.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.animeToday(AnimeCrawler.kt:217)
	at news-reporter-1.4.0.mirai.jar//online.ruin_of_future.reporter.tasks.MorningReportTask$run$1$1$2.invokeSuspend(MorningReportTask.kt:45)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at news-reporter-1.4.0.mirai.jar//online.ruin_of_future.reporter.tasks.MorningReportTask.run(MorningReportTask.kt:19)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by LinHeLurking** [comment]
报这个错误应该是当天没有番剧。正常情况下应该会在聊天里提示你今天没有番剧。如果聊天也有这个提示的话那就是一切正常的。这个报错只是后台记录了一下，没有什么问题的。实际上这个 Exception 是被正常捕获并处理的。

**Comment by LinHeLurking** [comment]
刚看了下好像确实是一个错误，新版本已经修复。
