### ISSUE TITLE
虚空推送

### ISSUE THREAD

**Issue by aipiao-gh** [LinHeLurking/mirai-news-reporter#23]
2022-12-16 07:00:05 V/Bot.2322981435: Group <- 早上好呀, 这是今天的 B 站番剧 \n( ?? ω ?? )?
2022-12-16 07:00:05 V/Bot.2322981435: Group <- 早上好呀, 这是今天的新闻速报 \nq(≧▽≦q)
2022-12-16 07:00:05 E/Reporter: javax.imageio.IIOException: Can't get input stream from URL!
javax.imageio.IIOException: Can't get input stream from URL!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407)
        at news-reporter-1.4.3.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler$writeOneAnimeInfo$oneAnimeImg$1.invokeSuspend(AnimeCrawler.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching i0.hdslb.com found.
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1329)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1151)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
        at java.base/java.net.URL.openStream(URL.java:1117)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1405)
        ... 9 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching i0.hdslb.com found.
        at java.base/sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:207)
        at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:98)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:459)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:434)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:233)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1313)
        ... 26 more

2022-12-16 07:00:06 E/Reporter: javax.net.ssl.SSLPeerUnverifiedException: Hostname zhuanlan.zhihu.com not verified:
    certificate: sha256/3PZZUpv7pGYs8pPznLO9I3ystqeMvzJJ0IJesy9+yiY=
    DN: CN=*.cdn.myqcloud.com
    subjectAltNames: [*.cdn.myqcloud.com, *.2144.cn, *.2144.com, *.4399.com, *.5054399.com, *.58cdn.com.cn, *.danmu.com, *.dpfile.com, *.ffnews.cn, *.file.myqcloud.com, *.flash.2144.com, *.flash.cn, *.image.myqcloud.com, *.img4399.com, *.sogoucdn.com, *.uniqlo.cn, *.vip.cdngot.com, *.vod.myqcloud.com, *.vod2.myqcloud.com, *.wanyabox.com, *.zhongcheng818.com, cdn.myqcloud.com, nitrome.com.4399.com, www.miniclip.com.4399pk.com]
javax.net.ssl.SSLPeerUnverifiedException: Hostname zhuanlan.zhihu.com not verified:
    certificate: sha256/3PZZUpv7pGYs8pPznLO9I3ystqeMvzJJ0IJesy9+yiY=
    DN: CN=*.cdn.myqcloud.com
    subjectAltNames: [*.cdn.myqcloud.com, *.2144.cn, *.2144.com, *.4399.com, *.5054399.com, *.58cdn.com.cn, *.danmu.com, *.dpfile.com, *.ffnews.cn, *.file.myqcloud.com, *.flash.2144.com, *.flash.cn, *.image.myqcloud.com, *.img4399.com, *.sogoucdn.com, *.uniqlo.cn, *.vip.cdngot.com, *.vod.myqcloud.com, *.vod2.myqcloud.com, *.wanyabox.com, *.zhongcheng818.com, cdn.myqcloud.com, nitrome.com.4399.com, www.miniclip.com.4399pk.com]
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:389)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at news-reporter-1.4.3.mirai.jar//okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at news-reporter-1.4.3.mirai.jar//online.ruin_of_future.reporter.crawler.HTTPGetter$get$2$future$1.invokeSuspend(HTTPGetter.kt:19)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at news-reporter-1.4.3.mirai.jar//online.ruin_of_future.reporter.crawler.HTTPGetter.get(HTTPGetter.kt:14)
        at news-reporter-1.4.3.mirai.jar//online.ruin_of_future.reporter.crawler.NewsCrawler$newsToday$newsDoc$1.invokeSuspend(NewsCrawler.kt:165)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by LinHeLurking** [comment]
你好，从报错信息来看是知乎那边的网站连接错误。可能是知乎的问题，也可能是你本地网络有些问题，这个我不确信。这个问题是临时性的还是持续性的？在此报错之前和之后，插件是否正常运行？

**Comment by aipiao-gh** [comment]
报错之前之后都正常运行,而且我是多个群都在推送,只有这个群推送失败,其他群都成功了

**Comment by LinHeLurking** [comment]
今天我也观察到了这个问题。不是很稳定，有时正常访问有时访问不到。可能是网络问题，也可能是知乎的限制。:(
