### ISSUE TITLE
安装了fontconfig还是启动报错，可以帮忙看看么

### ISSUE THREAD

**Issue by vafyl** [LinHeLurking/mirai-news-reporter#25]
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/38181587/209557422-f0e13dc8-5702-47bd-b079-facdda8e93d3.png">

**Comment by LinHeLurking** [comment]
从报错来看和之前缺 font config 的报错是类似的。应该还是和字体相关的报错。我猜跟发行版有关。

**Comment by QSlotus** [comment]
> 从报错来看和之前缺 font config 的报错是类似的。应该还是和字体相关的报错。我猜跟发行版有关。

我也出现了这样的问题。版本是Ubuntu 22.04.

**Comment by QSlotus** [comment]
报错信息：

```
2023-03-31 13:24:13 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service online.ruin_of_future.reporter.ReporterPlugin.
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:60)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:42)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:197)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:192)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:828)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:218)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.listPlugins(BuiltInJvmPluginLoaderImpl.kt:67)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:195)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:141)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:151)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:290)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
	at java.desktop/java.awt.Font.<clinit>(Font.java:288)
	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<init>(AnimeCrawler.kt:88)
	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<init>(AnimeCrawler.kt:79)
	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<clinit>(AnimeCrawler.kt:244)
	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.tasks.MorningReportTask.<init>(MorningReportTask.kt:17)
	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.ReporterPlugin.<clinit>(App.kt:30)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:51)
	... 36 more

```

**Comment by LinHeLurking** [comment]
> 报错信息：
> 
> ```
> 2023-03-31 13:24:13 E/main: Failed to init MiraiConsole.
> net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service online.ruin_of_future.reporter.ReporterPlugin.
> 	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:60)
> 	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:42)
> 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:197)
> 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:192)
> 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
> 	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)
> 	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
> 	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
> 	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
> 	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
> 	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
> 	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
> 	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:828)
> 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:218)
> 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.listPlugins(BuiltInJvmPluginLoaderImpl.kt:67)
> 	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
> 	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:195)
> 	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:141)
> 	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:151)
> 	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:290)
> 	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
> 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
> 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
> 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
> 	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
> 	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
> 	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
> 	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
> 	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
> 	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
> 	at org.itxtech.mcl.Loader.start(Loader.java:196)
> 	at org.itxtech.mcl.Loader.main(Loader.java:84)
> Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
> 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
> 	at java.base/java.lang.System.load(System.java:1953)
> 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
> 	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
> 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
> 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
> 	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
> 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
> 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
> 	at java.base/java.lang.System.loadLibrary(System.java:1989)
> 	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
> 	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
> 	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
> 	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
> 	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
> 	at java.desktop/java.awt.Font.<clinit>(Font.java:288)
> 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<init>(AnimeCrawler.kt:88)
> 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<init>(AnimeCrawler.kt:79)
> 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<clinit>(AnimeCrawler.kt:244)
> 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.tasks.MorningReportTask.<init>(MorningReportTask.kt:17)
> 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.ReporterPlugin.<clinit>(App.kt:30)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:467)
> 	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:51)
> 	... 36 more
> ```

看上去是 `Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so` 这里的问题，应该是却少 AWT 相关的库，可能是 Java 安装不完整导致的，参见 [这个 SO thread](https://stackoverflow.com/questions/67391845/exception-java-lang-unsatisfiedlinkerror-when-trying-to-open-allure-reports-in-w)。或者试试 [这个 comment 里的方法](https://github.com/LinHeLurking/mirai-news-reporter/issues/7#issuecomment-982246493)。

不确信这个能否解决问题，你可以试试看。

**Comment by Vectin64587** [comment]
> > 报错信息：
> > ```
> > 2023-03-31 13:24:13 E/main: Failed to init MiraiConsole.
> > net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service online.ruin_of_future.reporter.ReporterPlugin.
> > 	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:60)
> > 	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:42)
> > 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:197)
> > 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:192)
> > 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
> > 	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)
> > 	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
> > 	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
> > 	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
> > 	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
> > 	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
> > 	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
> > 	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:828)
> > 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:218)
> > 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.listPlugins(BuiltInJvmPluginLoaderImpl.kt:67)
> > 	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
> > 	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:195)
> > 	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:141)
> > 	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:151)
> > 	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:290)
> > 	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
> > 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
> > 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
> > 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
> > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> > 	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
> > 	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
> > 	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
> > 	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
> > 	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
> > 	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
> > 	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
> > 	at org.itxtech.mcl.Loader.start(Loader.java:196)
> > 	at org.itxtech.mcl.Loader.main(Loader.java:84)
> > Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
> > 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
> > 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
> > 	at java.base/java.lang.System.load(System.java:1953)
> > 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
> > 	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
> > 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
> > 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
> > 	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
> > 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
> > 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
> > 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
> > 	at java.base/java.lang.System.loadLibrary(System.java:1989)
> > 	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
> > 	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
> > 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
> > 	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
> > 	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
> > 	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
> > 	at java.desktop/java.awt.Font.<clinit>(Font.java:288)
> > 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<init>(AnimeCrawler.kt:88)
> > 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<init>(AnimeCrawler.kt:79)
> > 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.crawler.AnimeCrawler.<clinit>(AnimeCrawler.kt:244)
> > 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.tasks.MorningReportTask.<init>(MorningReportTask.kt:17)
> > 	at news-reporter-1.4.7.mirai.jar//online.ruin_of_future.reporter.ReporterPlugin.<clinit>(App.kt:30)
> > 	at java.base/java.lang.Class.forName0(Native Method)
> > 	at java.base/java.lang.Class.forName(Class.java:467)
> > 	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:51)
> > 	... 36 more
> > ```
> 
> 看上去是 `Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so` 这里的问题，应该是却少 AWT 相关的库，可能是 Java 安装不完整导致的，参见 [这个 SO thread](https://stackoverflow.com/questions/67391845/exception-java-lang-unsatisfiedlinkerror-when-trying-to-open-allure-reports-in-w)。或者试试 [这个 comment 里的方法](https://github.com/LinHeLurking/mirai-news-reporter/issues/7#issuecomment-982246493)。
> 
> 不确信这个能否解决问题，你可以试试看。

我在mirai的issue里找到了[这个](https://github.com/iTXTech/mirai-console-loader/issues/170#issuecomment-1443230805) 似乎是ssh客户端转发图形界面的锅
