### ISSUE TITLE
搜索番剧Not found info for date

### ISSUE THREAD

**Issue by YuiOfAstora** [LinHeLurking/mirai-news-reporter#3]
![Snipaste_2021-09-06_07-32-21](https://user-images.githubusercontent.com/40622185/132144376-3d40fb74-fa90-4e00-b45f-8f63a26597b5.png)

2021-09-06 07:29:56 I/Reporter: 赞美太阳 发起了动画请求...
2021-09-06 07:29:56 V/Bot.2845777804: Event: GroupMessagePreSendEvent(target=Group(), message=出错啦, 等会再试试吧 ￣へ￣)
2021-09-06 07:29:56 V/Bot.2845777804: Group() <- 出错啦, 等会再试试吧 ￣へ￣
2021-09-06 07:29:56 V/Bot.2845777804: Event: GroupMessagePostSendEvent(target=Group(), message=出错啦, 等会再试试吧 ￣へ￣, exception=null, receipt=net.mamoe.mirai.message.MessageReceipt@b8ff177)
2021-09-06 07:29:56 E/Reporter: java.lang.Exception: Not found info for date: 9-6
java.lang.Exception: Not found info for date: 9-6
        at online.ruin_of_future.reporter.AnimeCrawler.animeByDate(AnimeCrawler.kt:181)
        at online.ruin_of_future.reporter.AnimeCrawler.animeToday(AnimeCrawler.kt:192)
        at online.ruin_of_future.reporter.ReporterPlugin$onEnable$4$1$1.invokeSuspend(App.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by LinHeLurking** [comment]
谢谢, 我今天也发现了这个问题. 是这样的, 9-6 日真的是没有番剧的, 你可以在 B 站测试一下. 我今天修改了报错提示, 现在机器人会提示今天似乎没有番剧放送.
