### ISSUE TITLE
启动后报错直接关闭程序

### ISSUE THREAD

**Issue by Tamamoimoto** [LinHeLurking/mirai-news-reporter#6]
2021-09-28 09:34:28 I/main: Starting mirai-console...
2021-09-28 09:34:28 I/main: Backend: version 2.8.0-M1, built on 2021-09-22 17:49 :01.
2021-09-28 09:34:28 I/main: Frontend Terminal: version 2.7.1, provided by Mamoe  Technologies
2021-09-28 09:34:28 I/main: Welcome to visit https://mirai.mamoe.net/
2021-09-28 09:34:29 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load servi ce online.ruin_of_future.reporter.ReporterPlugin.
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService (PluginServiceHelper.kt:60)
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServ ices(PluginServiceHelper.kt:42)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$ex tractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:76)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$ex tractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:71)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:21 0)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Seq uences.kt:314)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:3 03)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt :214)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt :214)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Seq uences.kt:307)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:3 03)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt :786)
        at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:827)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.ex tractPlugins(BuiltInJvmPluginLoaderImpl.kt:95)
        at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPl ugins(FilePluginLoader.kt:51)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugin s(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSort AllPlugins(PluginManagerImpl.kt:186)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSort AllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:130)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPlug insUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:140)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doS tart$mirai_console(MiraiConsoleImplementationBridge.kt:157)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(Mi raiConsoleImplementation.kt:276)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa emon(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa emon$default(MiraiConsoleTerminalLoader.kt:151)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(Mira iConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:22 6)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:169 2)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j ava:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4 12)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:357 8)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j ava:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.j ava:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdap ter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java: 105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.j ava:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106 )
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService (PluginServiceHelper.kt:51)
        ... 53 more
Caused by: java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Unknown Source)
        at java.desktop/java.awt.Font.createFont(Unknown Source)
        at online.ruin_of_future.reporter.NewsCrawler.<init>(NewsCrawler.kt:25)
        at online.ruin_of_future.reporter.ReporterPlugin.<clinit>(App.kt:28)
        ... 56 more

root@VM-0-15-debian:~#

**Comment by Tamamoimoto** [comment]
Linux VM-0-15-debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64

**Comment by LinHeLurking** [comment]
谢谢反馈，能否给一点具体的信息呢？比如说是在做了什么操作之后出现的这个问题？

**Comment by Tamamoimoto** [comment]
> 谢谢反馈，能否给一点具体的信息呢？比如说是在做了什么操作之后出现的这个问题？

加了这个插件后就出现的问题，去掉这个插件后就可以启动了。

**Comment by LinHeLurking** [comment]
从报错来看是读取字体的问题。但是我在 Ubuntu 上没有成功复现这个 bug。不知道会不会是 JAVA API 的问题？我服务器上的 JAVA 版本是 

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by Tamamoimoto** [comment]
> 从报错来看是读取字体的问题。但是我在 Ubuntu 上没有成功复现这个 bug。不知道会不会是 JAVA API 的问题？我服务器上的 JAVA 版本是
> 
> ```
> openjdk version "11.0.11" 2021-04-20
> OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
> OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
> ```

我是debian系统，
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

**Comment by LinHeLurking** [comment]
依然没能复现这个问题。我试着换了几个 OS 和 JAVA 都没有出现这种在启动阶段就崩溃的情况。你这个 reporter 插件是自行编译的还是从 release 页面下载的呢？如果是自己编译的我猜是打包没有把字体打包进去。

**Comment by Tamamoimoto** [comment]
> 依然没能复现这个问题。我试着换了几个 OS 和 JAVA 都没有出现这种在启动阶段就崩溃的情况。你这个 reporter 插件是自行编译的还是从 release 页面下载的呢？如果是自己编译的我猜是打包没有把字体打包进去。

release 页面下载的，一个月前了。我现在再试试看看。

**Comment by Tamamoimoto** [comment]
root@VM-0-15-debian:~# ./mcl
  16:57:53 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  16:57:53 [INFO] https://github.com/iTXTech/mirai-console-loader
  16:57:53 [INFO] This program is licensed under GNU AGPL v3
  16:57:55 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  16:57:56 [INFO] Verifying "net.mamoe:mirai-console" v2.8.0-M1
  16:57:56 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.8.0-M1
  16:57:56 [INFO] Verifying "net.mamoe:mirai-core-all" v2.8.0-M1
  16:57:58 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  16:57:58 [INFO] Fetching Mirai Console Loader Announcement...
  16:57:58 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

2021-10-29 16:58:00 I/main: Starting mirai-console...
2021-10-29 16:58:00 I/main: Backend: version 2.8.0-M1, built on 2021-09-22 17:49              :01.
2021-10-29 16:58:00 I/main: Frontend Terminal: version 2.8.0-M1, provided by Mam              oe Technologies
2021-10-29 16:58:00 I/main: Welcome to visit https://mirai.mamoe.net/
2021-10-29 16:58:01 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load servi              ce online.ruin_of_future.reporter.ReporterPlugin.
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService              (PluginServiceHelper.kt:60)
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServ              ices(PluginServiceHelper.kt:42)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$ex              tractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:76)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$ex              tractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:71)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:21              0)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Seq              uences.kt:314)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:3              03)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt              :214)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt              :214)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Seq              uences.kt:307)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:3              03)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt              :786)
        at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:827)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.ex              tractPlugins(BuiltInJvmPluginLoaderImpl.kt:95)
        at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPl              ugins(FilePluginLoader.kt:51)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugin              s(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSort              AllPlugins(PluginManagerImpl.kt:186)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSort              AllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:130)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPlug              insUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:140)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doS              tart$mirai_console(MiraiConsoleImplementationBridge.kt:157)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(Mi              raiConsoleImplementation.kt:276)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa              emon(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa              emon$default(MiraiConsoleTerminalLoader.kt:151)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(Mira              iConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ              e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow              n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un              known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ              e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow              n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un              known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:22              6)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:169              2)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j              ava:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4              12)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:357              8)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j              ava:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.j              ava:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdap              ter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:              105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.j              ava:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106              )
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService              (PluginServiceHelper.kt:51)
        ... 53 more
Caused by: java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Unknown Source)
        at java.desktop/java.awt.Font.createFont(Unknown Source)
        at online.ruin_of_future.reporter.NewsCrawler.<init>(NewsCrawler.kt:25)
        at online.ruin_of_future.reporter.ReporterPlugin.<clinit>(App.kt:28)
        ... 56 more
还是打不开，加进去直接崩掉，删掉就能打开。

**Comment by fatinghenji** [comment]
同样问题，报错代码如下：
```java
2022-02-16 17:11:45 E/main: Failed to init MiraiConsole.                                                                                                                    [22/1089]
net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service online.ruin_of_future.reporter.ReporterPlugin.                                                    
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:60)                                                                          
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:42)                                                                      
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:84)                             
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$findAllInstances$2.invoke(BuiltInJvmPluginLoaderImpl.kt:79)                             
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)                                                                                                   
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)                                                                                       
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)                                                                                                  
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)                                                                                                
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)                                                                                                
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)                                                                                       
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)                                                                                                  
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)                                                                                                
        at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:827)                                                                                                       
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:103)                                                      
        at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPlugins(FilePluginLoader.kt:51)                                                                        
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)                                                                                
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:191)                                                                 
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:135)                                              
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:145)                                       
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:151)                                          
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:392)                                                                     
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:156)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:155)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:51)
        ... 53 more
Caused by: java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Unknown Source)
        at java.desktop/java.awt.Font.createFont(Unknown Source)
        at online.ruin_of_future.reporter.NewsCrawler.<init>(NewsCrawler.kt:25)
        at online.ruin_of_future.reporter.ReporterPlugin.<clinit>(App.kt:27)
        ... 56 more
```
系统是`Linux localhost 4.4.296-perf+ #1 SMP PREEMPT Thu Feb 3 06:11:46 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
不太清楚怎么查看java版本

**Comment by zhaoZiQu** [comment]
同报错，电脑上和服务器(linux)上都是jdk16，电脑上没有问题和报错，可以正常使用，服务器上会出现如同楼上得报错

**Comment by LinHeLurking** [comment]
> 同报错，电脑上和服务器(linux)上都是jdk16，电脑上没有问题和报错，可以正常使用，服务器上会出现如同楼上得报错

好的，我去检查一下是什么原因。

**Comment by zhaoZiQu** [comment]
> > 同报错，电脑上和服务器(linux)上都是jdk16，电脑上没有问题和报错，可以正常使用，服务器上会出现类似楼上得报错
> 
> 好，我去检查一下是什么原因。

多谢

**Comment by LinHeLurking** [comment]
成功复现了本问题。应该不是插件的问题，在服务器上安装 fontconfig 这个包即可。不同的系统里面包的名字可能略有差别，安装的时候注意一下就行。

谢谢你们的反馈。
@zhaoZiQu @Tamamoimoto @fatinghenji

**Comment by zhaoZiQu** [comment]
> 成功复现了本本。应该不是插件的注意问题，在服务器上安装fontconfig 可以安装不同的系统里面包的名字可能另外一下，此时的注意问题就行了。
> 
> 谢谢你们的反馈。 @zhaoZiQu @Tamamoimoto @fatinghenji

感谢

**Comment by zhaoZiQu** [comment]
成功解决
