### ISSUE TITLE
无法搜索今日番剧

### ISSUE THREAD

**Issue by skyfsj** [LinHeLurking/mirai-news-reporter#8]
MiraiConsole版本： v2.6.5
操作系统：Windows Server 2008
已加载插件：
AntiLightappShare-0.13.6.mirai.jar
bilibili-helper-1.1.6.mirai.jar
mirai-console-mcmod-plugin-1.1.2.mirai.jar
mirai-console-minecraft-plugin-1.1.5.mirai.jar
mirai-native-2.0.0-beta.1.jar
news-reporter-1.2.10.mirai.jar

报错信息：
2021-10-08 00:45:56 I/Reporter: fsj 发起了动画请求...
2021-10-08 00:45:56 V/Bot.******: Group(******) <- 这是今天的 B 站番剧 (
•̀ ω •́ )✧
2021-10-08 00:45:57 V/Bot.******: Group(******) <- 出错啦, 等会再试试吧
￣へ￣
2021-10-08 00:45:57 E/Reporter: kotlinx.serialization.json.internal.JsonDecoding
Exception: Unexpected JSON token at offset 75: Encountered an unknown key 'date_
ts'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....e":"10-2","date_ts":1633104000,"day_of_week":6,"is_today":0,...
..
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token
 at offset 75: Encountered an unknown key 'date_ts'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....e":"10-2","date_ts":1633104000,"day_of_week":6,"is_today":0,...
..
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingExce
ption(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingExce
ption(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:338
)
        at kotlinx.serialization.json.internal.JsonReader.fail$default(JsonReade
r.kt:337)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObject
Index(StreamingJsonDecoder.kt:144)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElemen
tIndex(StreamingJsonDecoder.kt:87)
        at online.ruin_of_future.reporter.ResultByDate$$serializer.deserialize(A
nimeCrawler.kt:47)
        at online.ruin_of_future.reporter.ResultByDate$$serializer.deserialize(A
nimeCrawler.kt:47)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableV
aluePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerial
izableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValu
e(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElem
ent(AbstractDecoder.kt:70)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSe
rializableElement$default(Decoding.kt:536)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(Collect
ionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readEleme
nt$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(Col
lectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deseriali
ze(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableV
aluePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerial
izableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValu
e(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElem
ent(AbstractDecoder.kt:70)
        at online.ruin_of_future.reporter.TimeLineInfo$$serializer.deserialize(A
nimeCrawler.kt:60)
        at online.ruin_of_future.reporter.TimeLineInfo$$serializer.deserialize(A
nimeCrawler.kt:60)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableV
aluePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerial
izableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at online.ruin_of_future.reporter.AnimeCrawler.getData(AnimeCrawler.kt:2
10)
        at online.ruin_of_future.reporter.AnimeCrawler.animeByDate(AnimeCrawler.
kt:178)
        at online.ruin_of_future.reporter.AnimeCrawler.animeToday(AnimeCrawler.k
t:197)
        at online.ruin_of_future.reporter.ReporterPlugin$onEnable$sendAnimeToTar
get$1.invokeSuspend(App.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)

**Comment by LinHeLurking** [comment]
谢谢反馈，我查了一下，发现是 B 站的 API 变了。我尽快修复。

**Comment by LinHeLurking** [comment]
这个情况只在有番剧停播的时候会出现。之前写的时候没注意到这个情况。目前已经修复，过几分钟之后就能在 release 里面找到啦。
