### ISSUE TITLE
番剧功能无法使用

### ISSUE THREAD

**Issue by InzamZ** [LinHeLurking/mirai-news-reporter#9]
你好，我的番剧功能是无法使用

使用的服务器端系统 CentOS7 
mirai 2.7.1
openjdk version "11.0.12" 2021-07-20 LTS

2021-10-29 23:12:42 : Event: GroupMessagePostSendEvent(, message=出错啦, 等会再试试吧 ￣へ￣, exception=null, receipt=net.mamoe.mirai.message.MessageReceipt@1deb6682)
2021-10-29 23:12:42 E/Reporter: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1524: Encountered an unknown key 'delay_id'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....f69c64487efad.png","delay":1,"delay_id":400,"delay_index":"第.....
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1524: Encountered an unknown key 'delay_id'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....f69c64487efad.png","delay":1,"delay_id":400,"delay_index":"第.....
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.JsonLexer.fail(JsonLexer.kt:479)
	at kotlinx.serialization.json.internal.JsonLexer.failOnUnknownKey(JsonLexer.kt:475)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:154)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:143)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:75)
	at online.ruin_of_future.reporter.AnimeInfo$$serializer.deserialize(AnimeCrawler.kt:19)
	at online.ruin_of_future.reporter.AnimeInfo$$serializer.deserialize(AnimeCrawler.kt:19)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at online.ruin_of_future.reporter.ResultByDate$$serializer.deserialize(AnimeCrawler.kt:47)
	at online.ruin_of_future.reporter.ResultByDate$$serializer.deserialize(AnimeCrawler.kt:47)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at online.ruin_of_future.reporter.TimeLineInfo$$serializer.deserialize(AnimeCrawler.kt:60)
	at online.ruin_of_future.reporter.TimeLineInfo$$serializer.deserialize(AnimeCrawler.kt:60)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
	at online.ruin_of_future.reporter.AnimeCrawler.getData(AnimeCrawler.kt:210)
	at online.ruin_of_future.reporter.AnimeCrawler.animeByDate(AnimeCrawler.kt:178)
	at online.ruin_of_future.reporter.AnimeCrawler.animeToday(AnimeCrawler.kt:197)
	at online.ruin_of_future.reporter.ReporterPlugin$onEnable$sendAnimeToTarget$1.invokeSuspend(App.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by LinHeLurking** [comment]
这个好像和之前报的 BUG 是一样的。目前已经在最新版本的插件修复了。你可以用 release 页面的最新版本试试看。

**Comment by InzamZ** [comment]
谢谢，问题已经解决了！今天早上就可以正常运行了
